using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ASP_Empty_WebApplication_01.Models;

/// <summary>
/// Representation of a single task item in the payload.
/// Fields mirror the JSON keys used by the client.
/// </summary>
public class TaskItem
{
    // IDs are generated by client with Date.now() or numeric values in examples,
    // so long is a safe choice.
    [JsonPropertyName("id")]
    public long Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    // Client uses "YYYY-MM-DD" strings in many places; keep raw string to avoid parsing surprises.
    // If you prefer DateTime on deserialization, replace these with DateTime and add converters.
    [JsonPropertyName("startDate")]
    public string? StartDate { get; set; }

    [JsonPropertyName("endDate")]
    public string? EndDate { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("completed")]
    public bool Completed { get; set; }

    // Nullable integer 0..100; null means not tracked / completed states use null in client code
    [JsonPropertyName("progress")]
    public int? Progress { get; set; }

    // Optional helpers often used by backends: a deleted flag or metadata the client may send
    [JsonPropertyName("deleted")]
    public bool? Deleted { get; set; }

    /// <summary>
    /// Attempts to parse StartDate into DateTime if possible.
    /// Returns null when parsing fails or StartDate is null/empty.
    /// Parsing assumes yyyy-MM-dd or ISO formats; adjust if your client sends different formats.
    /// </summary>
    public DateTime? StartDateAsDateTime()
    {
        if (string.IsNullOrWhiteSpace(StartDate)) return null;
        if (DateTime.TryParse(StartDate, out var dt)) return DateTime.SpecifyKind(dt.Date, DateTimeKind.Utc);
        return null;
    }

    /// <summary>
    /// Attempts to parse EndDate into DateTime if possible.
    /// </summary>
    public DateTime? EndDateAsDateTime()
    {
        if (string.IsNullOrWhiteSpace(EndDate)) return null;
        if (DateTime.TryParse(EndDate, out var dt)) return DateTime.SpecifyKind(dt.Date, DateTimeKind.Utc);
        return null;
    }

    /// <summary>
    /// Normalizes the task fields to keep invariants:
    /// - Ensure Completed is boolean (already typed)
    /// - Ensure Progress is either null or within 0..100
    /// - If Progress >= 100 -> mark Completed = true and Progress = null
    /// - If Completed == true, clear Progress (set null)
    /// Call this before saving or further processing.
    /// </summary>
    public void Normalize()
    {
        // Coerce progress to valid range or null
        if (Progress.HasValue)
        {
            var p = Progress.Value;
            if (p < 0) p = 0;
            if (p > 100) p = 100;
            Progress = p;
        }

        if (Progress.HasValue && Progress.Value >= 100)
        {
            Completed = true;
            Progress = null;
        }

        if (Completed)
        {
            Progress = null;
        }
    }
}
